{% set version = "4.6.3" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-cobalt
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/cobalt_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/cobalt/cobalt_{{ version }}.tar.gz
  sha256: adb28d8553d37a0ff4c30069f9626a73055fb75f6cb37caa6fc7e642a3723872

build:
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-arg >=0.1.1
    - r-cli >=3.6.5
    - r-ggplot2 >=4.0.0
    - r-gridextra >=2.3
    - r-gtable >=0.3.6
    - r-rlang >=1.2.0
  run:
    - r-base
    - r-arg >=0.1.1
    - r-cli >=3.6.5
    - r-ggplot2 >=4.0.0
    - r-gridextra >=2.3
    - r-gtable >=0.3.6
    - r-rlang >=1.2.0

test:
  commands:
    - $R -e "library('cobalt')"           # [not win]
    - "\"%R%\" -e \"library('cobalt')\""  # [win]

about:
  home: https://ngreifer.github.io/cobalt/
  dev_url: https://github.com/ngreifer/cobalt
  license: GPL-2.0-or-later
  summary: Generate balance tables and plots for covariates of groups preprocessed through matching, weighting or subclassification, for example, using propensity scores. Includes integration with 'MatchIt', 'twang', 'Matching', 'optmatch', 'CBPS', 'ebal', 'WeightIt', 'cem', 'sbw', and 'designmatch' for assessing 
    balance on the output of their preprocessing functions. Users can also specify data for balance assessment not generated through the above packages. Also included are methods for assessing balance in clustered or multiply imputed data sets or data sets with longitudinal treatments.
  license_family: GPL2
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
