{% set version = "4.5.1" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-cobalt
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/cobalt_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/cobalt/cobalt_{{ version }}.tar.gz
  sha256: 799b68805033a92900c5a884862a315670b0379ed8fc8c3f3c20c61e402c27c0

build:
  merge_build_host: true  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip      # [win]
  host:
    - r-base
    - r-backports >=1.1.9
    - r-chk >=0.8.1
    - r-crayon
    - r-ggplot2 >=3.4.1
    - r-gridextra >=2.3
    - r-gtable >=0.3.0
    - r-rlang >=0.4.0
  run:
    - r-base
    - r-backports >=1.1.9
    - r-chk >=0.8.1
    - r-crayon
    - r-ggplot2 >=3.4.1
    - r-gridextra >=2.3
    - r-gtable >=0.3.0
    - r-rlang >=0.4.0

test:
  commands:
    - $R -e "library('cobalt')"           # [not win]
    - "\"%R%\" -e \"library('cobalt')\""  # [win]

about:
  home: https://ngreifer.github.io/cobalt/
  dev_url: https://github.com/ngreifer/cobalt
  license: GPL-2.0-or-later
  summary: Generate balance tables and plots for covariates of groups preprocessed through matching, weighting or subclassification, for example, using propensity scores. Includes integration with 'MatchIt', 'twang', 'Matching', 'optmatch', 'CBPS', 'ebal', 'WeightIt', 'cem', 'sbw', and 'designmatch' for assessing balance
    on the output of their preprocessing functions. Users can also specify data for balance assessment not generated through the above packages. Also included are methods for assessing balance in clustered or multiply imputed data sets or data sets with longitudinal treatments.
  license_family: GPL2
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
